baseURL: "https://aidea775.github.io/"
languageCode: es
defaultContentLanguage: es
summaryLength: 10
title: AIDEA775 en español

markup:
  tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 1
  highlight:
    style: dracula

languages:
  es:
    params:
      logo:
        title: "AIDEA775"
        subtitle: "en español"